### ISSUE TITLE
Icon Request: NXC

### ISSUE THREAD

**Issue by nloomans** [file-icons/source#11]
NXC is a programming language for the LEGO NXT Robot, it uses the extension `.nxc`.
It doesn't have an official icon, but a simplified version of the brick will do fine:
![nxtbluetoothsymbol](https://cloud.githubusercontent.com/assets/7829481/24557038/9fcc2930-1636-11e7-97a3-c0b4e275aca5.gif)

By the way, thanks a lot for making this awesome package!

**Comment by Alhadis** [comment]
Hey mate, sorry for taking so long to get back to you. Will this be okay?

<img src="https://cloud.githubusercontent.com/assets/2346707/24607978/b1b33a52-18b7-11e7-8a7b-fc4d67378586.png" width="168" alt="Figure 1" />

I exaggerated some details in order to make it more recognisable at icon-size:

<img src="https://cloud.githubusercontent.com/assets/2346707/24607978/b1b33a52-18b7-11e7-8a7b-fc4d67378586.png" width="16" alt="Figure 1" />

**Comment by Alhadis** [comment]
Few more modifications. It'll look like this in Atom:

<img src="https://cloud.githubusercontent.com/assets/2346707/24612046/7087761e-18c7-11e7-9a02-69cf1bcbbda4.png" alt="Figure 2" width="214" />

**Comment by nloomans** [comment]
Thanks! That will do nicely.
