### ISSUE TITLE
Styled-Components

### ISSUE THREAD

**Issue by justduy** [file-icons/source#39]
Icon: 
https://www.npmjs.com/package/styled-icons
![image](https://user-images.githubusercontent.com/8453104/40242014-b95993a8-5abc-11e8-8943-02d06d3266bc.png)

would be great to be able to use this, as my project no longer uses .css files, rather .sc.js files.

**Comment by Alhadis** [comment]
I don't see an icon. Just an emoji:

<img src="https://user-images.githubusercontent.com/2346707/40242326-bd6af38a-5b00-11e8-8ba4-83af615837a9.png" width="341" alt="Figure 1" />

Is that what you're referring to?

**Comment by justduy** [comment]
Yeah, would be great to be able to have icons to differentiate Styled-Components stylesheet from normal js files

**Comment by Alhadis** [comment]
Oooh, right. You want an icon for `.sc.js` files. 😄

Normally, I'd recommend you add this to your stylesheet instead, since it's just an emoji...

~~~less
.icon[data-name$=".sc.js"]::before{
	content: "💅";
	font-family: inherit;
}
~~~

However, oddly enough, that exact graphic is used by [their branding](https://github.com/styled-components/brand/blob/d02216b/styled-components.png), so I guess it makes it more "official". I'll add a 2-colour version of it later. 😉
