### ISSUE TITLE
[Adding new icons to the package] Prolog Icon 

### ISSUE THREAD

**Issue by yochem** [file-icons/source#45]
Hey, i would love to see a prolog specific icon. The current icon in Atom on a `.pl` file is this one:

![](https://user-images.githubusercontent.com/23235841/46422510-d45ea780-c734-11e8-9fe2-ab1e861707aa.png)

I searched through [charmap.md](
https://github.com/file-icons/source/blob/master/charmap.md) but couldn't find the specific icon. I guess it's from perl, given the `.pl` file extension. I found a prolog icon [here](https://iconscout.com/icon/prolog). It's MIT licensed. Is it possible to add this to this package? Or is there something I forgot?

![](https://cdn.iconscout.com/icon/free/png-256/prolog-458170.png)

**Comment by Alhadis** [comment]
:wave: Hi @yochem,

We actually have a [Prolog icon already](https://github.com/file-icons/DevOpicons/blob/master/svg/prolog.svg). The reason you're seeing the Perl icon is because the package (currently) has no way to differentiate two languages which use the same file extension. Because Perl has more widespread use than Prolog, it's used as the default.

This is less than ideal, I know, but you can make the Prolog icon appear for all `.pl` files by [adding a custom language](https://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-language-recognition) mapping:

~~~cson
"*":
	customFileTypes:
		"source.prolog": [
			"pl
		]
~~~

I hope to address this in a future release by implementing heuristics to disambiguate filetypes.

**Comment by yochem** [comment]
awesome! Thank you for this. 🍻
