### ISSUE TITLE
Missing Icons?

### ISSUE THREAD

**Issue by skipjack** [file-icons/source#50]
So I might just be missing something, but I can't find the svgs for certain icons that are supported by the `atom` package. For example I see `js-icon` mentioned [here][1] but no corresponding file in the [`/svg`][2] directory. The [`html5-icon`][3] is another one I couldn't find in [`/svg`][2].

Is the exclusion intentional or am I missing something?

[1]: https://github.com/file-icons/atom/blob/master/lib/icons/.icondb.js#L136-L137
[2]: https://github.com/file-icons/source/tree/master/svg
[3]: https://github.com/file-icons/atom/blob/master/lib/icons/.icondb.js#L129-L130

**Comment by skipjack** [comment]
I did look here as well and didn't see anything about those icons (and a few others) mentioned:

https://github.com/file-icons/source/blob/master/charmap.md

**Comment by skipjack** [comment]
I seem to have found the missing ones here:
https://github.com/file-icons/DevOpicons/tree/master/svg

Happy to close this now but if anyone has a second to explain to me the difference between the two I would appreciate it. Maybe a sentence or two in the README would clarify this situation for others like me who are looking for the raw SVGs.

**Comment by Alhadis** [comment]
Hi @skipjack,

Yes, the package is composed of multiple icon-fonts. The reason for this fragmentation is an unfortunate accident of history: when the `file-icons` package started (before my involvement), it was a collection of existing icon-fonts without the controlled collection we have today. There were actually a few other custom icon-fonts which I merged together as part of a clean-up when I first started contributing.

However, I couldn't merge the larger icon-fonts (Devicons and Mfizz) because their codepoints conflicted — and their icons were already in use by users who customised their stylesheets. In an effort to retain backwards compatibility, I only added new icons to the package's custom font. I didn't expect the font to get this big; it started as a handful of bespoke icons which didn't exist anywhere else at the time.

I hope that answers your question. If not, let me know. :+1:

**Comment by skipjack** [comment]
Thank you for the detailed explanation, that does clear things up.

> However, I couldn't merge the larger icon-fonts (Devicons and Mfizz) because their codepoints conflicted — and their icons were already in use by users who customised their stylesheets. In an effort to retain backwards compatibility, I only added new icons to the package's custom font.

Yeah, I totally understand how that would be a breaking change now and I'm not sure how all these repos are packaged/distributed so I the desire to avoid surprising users with broken icons.

That said (and it sounds like you agree), despite the fact that these have been aggregated from different places, it would definitely be useful to have a single set of SVGs with the same aspect ratio and a single backing font for users to consume. Definitely would take some work though and we'd have to figure out a distribution plan that doesn't hurt users. I'm guessing this is long term if doable at all.

In the short term though, would you be open to a PR here to update the README? I think what threw me off was the fact that `file-icons/source` sounded like the home for all icons used in the repos. I'm going to close this issue but happy to keep talking if you're open to these points.

**Comment by Alhadis** [comment]
> In the short term though, would you be open to a PR here to update the README?

If you'd like. :+1:

> Definitely would take some work though and we'd have to figure out a distribution plan that doesn't hurt users. I'm guessing this is long term if doable at all.

Yeah, that's definitely under consideration (and has been for some time now), but what makes things difficult is deciding how to go about separating the package's [format database](https://github.com/file-icons/atom/blob/master/config.cson) to the underlying icon-font(s). Keeping it in sync is a pain; we don't have a proper build system yet, but that's something I intend to address in time. Exactly how is uncertain; hence the reason for the readme's terseness.

**Comment by TicTak21** [comment]
@Alhadis, hi. 

So there is no `file-icons/source`? 
Are you planning to add something like this?
